### ISSUE TITLE
Failure when nuget package is not added via PackageReference

### ISSUE THREAD

**Issue by NickSpag** [nor0x/AppCenter-XMac#11]
First, great work @nor0x, and thanks for doing this! It's been a giant pain/gap in the Xamarin.Mac story.

### Issue:
Using the library requires that your project has been migrated to restore packages via `PackageReference` nodes. When adding your package in the older `Reference` format it creates a bunch of messy hint paths, you see the bad-target AppCenter Assert in the console, and it generally doesn't work.

Unfortunately, VS4Mac's Xamarin.Mac templates still seem to use the older Reference style. 

### Suggestions:
I'm not familiar enough with msbuild to make any diagnoses on the actual problem, but I can follow this issue with a little PR making a note in the readme that should at least help people headoff any confusion. Most people are probably switching towards PackageReference by now anyway, so I'm not sure how large a barrier this is. But would help to clarify.

**Comment by nor0x** [comment]
thanks for the issue and the PR. The readme is updated now, i'm not sure how wide spread the old `Reference` still is, i personally have migrated to `PackageReference` a while ago. 

let's keep this issue open and see how big the demand for `Reference` is.

**Comment by NickSpag** [comment]
yea, agreed, I'm not sure either. I'm "surprised" the vs4m xamarin.mac templates are still on the style, which is how I got caught.

**Comment by nor0x** [comment]
this code now lives in the official repository https://github.com/microsoft/appcenter-sdk-dotnet

if you still have this issue - please open a new one here:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/new/choose
