### ISSUE TITLE
Crashes are not reported in AppCenter

### ISSUE THREAD

**Issue by rkops-bd** [nor0x/AppCenter-XMac#16]
First of all, signed builds are working with the 4.0.0 release, much thanks!!

Handled, but also unhandled exceptions are not visible in the Diagnose/Issues.
In the logflow are they visible only with an error_id.
Any idea?

**Comment by nor0x** [comment]
thanks for the report @rkops-bd. This is a strange one because i have just tested the bindings with the demo app and was able to see errors and exceptions.

In the Logflow however i'm also seeing the `error_id` this is the same on iOS though, so i guess we don't get more information in the log flow.
![IMG_9829](https://user-images.githubusercontent.com/3210391/100277927-48d3b080-2f64-11eb-95fa-730a26d27866.jpg)


In Diagnostics -> Issues i can see more details. Keep in mind that for handled exceptions you have to add `&errorType=all ` to the url.
![IMG_210212](https://user-images.githubusercontent.com/3210391/100277839-22ae1080-2f64-11eb-976d-3c379cf74b66.jpg)

![IMG_210213](https://raw.githubusercontent.com/nor0x/AppCenter-XMac/develop/ProTips/IMG_8102833.jpg)

**Comment by jlewicki-nevo** [comment]
For what its worth, I am not seeing any crashes being reported in the AppCenter dashboard either.

I do see something like this in the application output, 

```
2020-12-03 11:24:49.492 Eureka.MacOS[89970:6566412] [AppCenterCrashes] ERROR: +[MSACWrapperLogger MSACWrapperLog:tag:level:]/10 Unhandled Exception:
Microsoft.AppCenter.Crashes.TestCrashException: Test crash exception generated by SDK
  at Microsoft.AppCenter.Crashes.Crashes.GenerateTestCrash () [0x00005] in <11d2273d68084ba690cc0e85f7f9ecf2>:0 
  at Eureka.MacOS.AppDelegate.ApplicationShouldTerminateAfterLastWindowClosed (AppKit.NSApplication sender) 
--- End of stack trace from previous location where exception was thrown ---

```

So it looks like the Crashes handler is being invoked? But somehow the error data is not making it to AppCenter?

**Comment by nor0x** [comment]
thanks for the info @jlewicki-nevo  - in your case it was working before (i.e. with package version 3.4.3). I will investigate it and see which changes could cause this error

**Comment by nor0x** [comment]
i have just published version 4.1.0 of the bindings - on the apple side it fixed a regression with crash reporting. could you try if this version fixes the issue for you? I have also updated the demo project in this repository, but this demo was working with version 4.0.0 as well

**Comment by LuisM000** [comment]
Hi, 

I am testing with NuGet in my project and with demo project and I do not see any crash in the panel (handle errors and traces shows correctly). 
In the macOS console it does seem that the exception is caught correctly.

`[AppCenterCrashes] ERROR: +[MSACWrapperLogger MSACWrapperLog:tag:level:]/10 Unhandled Exception:
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Exception: Exception of type 'System.Exception' was thrown.
  at Application.Pages.Confirmation.ConfirmationView..ctor () [0x00006] in <78d01a6f400a461fbf6e33ce7299b3a4>:0 
  at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.<…>
[AppCenterCrashes] INFO: +[MSACWrapperLogger MSACWrapperLog:tag:level:]/10 Saving wrapper exception...
[AppCenterCrashes] INFO: +[MSACWrapperLogger MSACWrapperLog:tag:level:]/10 Saved wrapper exception.`


For what it's help, after an unhandled exception, when opening the app again and after initializing the AppCenter, if I look at Crashes.HasCrashedInLastSessionAsync (), it always returns false.

Any idea what may be happening?

Thanks for the effort nor0x :)

**Comment by nor0x** [comment]
Hi @LuisM000 👋
i have just updated the bindings to the latest versions and fixed some bugs on the macOS side, could you test again with the latest version? Did some tests in the demo project where reporting works fine

**Comment by nor0x** [comment]
this code now lives in the official repository https://github.com/microsoft/appcenter-sdk-dotnet

if you still have this issue - please open a new one here:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/new/choose
