### ISSUE TITLE
App Store failed

### ISSUE THREAD

**Issue by Suplanus** [nor0x/AppCenter-XMac#17]
I build my release with:
- `codesign --deep`
- `<LinkMode>None</LinkMode>`

Transporter worked well. But I got this email from App Store Connect:

>Please correct the following issues, then upload again.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenter (Cuterdio.app/Contents/Frameworks/AppCenter.framework) must contain a symbolic link 'AppCenter' -> 'Versions/Current/AppCenter'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenter (Cuterdio.app/Contents/Frameworks/AppCenter.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenter (Cuterdio.app/Contents/Frameworks/AppCenter.framework) contains 'Headers', which should be a symbolic link -> 'Versions/Current/Headers'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90292: Malformed Framework - The framework bundle AppCenter (Cuterdio.app/Contents/Frameworks/AppCenter.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenterAnalytics (Cuterdio.app/Contents/Frameworks/AppCenterAnalytics.framework) must contain a symbolic link 'AppCenterAnalytics' -> 'Versions/Current/AppCenterAnalytics'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenterAnalytics (Cuterdio.app/Contents/Frameworks/AppCenterAnalytics.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenterAnalytics (Cuterdio.app/Contents/Frameworks/AppCenterAnalytics.framework) contains 'Headers', which should be a symbolic link -> 'Versions/Current/Headers'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90292: Malformed Framework - The framework bundle AppCenterAnalytics (Cuterdio.app/Contents/Frameworks/AppCenterAnalytics.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenterCrashes (Cuterdio.app/Contents/Frameworks/AppCenterCrashes.framework) must contain a symbolic link 'AppCenterCrashes' -> 'Versions/Current/AppCenterCrashes'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenterCrashes (Cuterdio.app/Contents/Frameworks/AppCenterCrashes.framework) must contain a symbolic link 'Resources' -> 'Versions/Current/Resources'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90291: Malformed Framework - The framework bundle AppCenterCrashes (Cuterdio.app/Contents/Frameworks/AppCenterCrashes.framework) contains 'Headers', which should be a symbolic link -> 'Versions/Current/Headers'. Refer to the Anatomy of Framework Bundles for more information.
>
>ITMS-90292: Malformed Framework - The framework bundle AppCenterCrashes (Cuterdio.app/Contents/Frameworks/AppCenterCrashes.framework) 'Versions' directory must contain a symbolic link 'Current' resolving to a specific version directory. Resolved link target: '${linkTarget}'. Refer to the Anatomy of Framework Bundles for more information.

**Comment by nor0x** [comment]
Hi @Suplanus 👋

finally found some time to investigate this issue. I'm now generating the correct Anatomy in the bundled `.framework` directories. Now they have the following structure


```
AppCenter.framework
├── AppCenter -> Versions/A/AppCenter
├── Resources -> Versions/A/Resources
└── Versions
    ├── A
    │   ├── AppCenter
    │   ├── Resources
    │   │   └── Info.plist
    │   └── _CodeSignature
    │       ├── CodeDirectory
    │       ├── CodeEntitlements
    │       ├── CodeRequirements
    │       ├── CodeRequirements-1
    │       ├── CodeResources
    │       └── CodeSignature
    └── Current -> A

AppCenterAnalytics.framework
├── AppCenterAnalytics -> Versions/A/AppCenterAnalytics
├── Resources -> Versions/A/Resources
└── Versions
    ├── A
    │   ├── AppCenterAnalytics
    │   ├── Resources
    │   │   └── Info.plist
    │   └── _CodeSignature
    │       ├── CodeDirectory
    │       ├── CodeEntitlements
    │       ├── CodeRequirements
    │       ├── CodeRequirements-1
    │       ├── CodeResources
    │       └── CodeSignature
    └── Current -> A

AppCenterCrashes.framework
├── AppCenterCrashes -> Versions/A/AppCenterCrashes
├── Resources -> Versions/A/Resources
└── Versions
    ├── A
    │   ├── AppCenterCrashes
    │   ├── Resources
    │   │   └── Info.plist
    │   └── _CodeSignature
    │       ├── CodeDirectory
    │       ├── CodeEntitlements
    │       ├── CodeRequirements
    │       ├── CodeRequirements-1
    │       ├── CodeResources
    │       └── CodeSignature
    └── Current -> A
```

let's see if this fixes the issue

**Comment by Suplanus** [comment]
A big thank you. Give me some time, I will have a look into it 🦄

**Comment by Suplanus** [comment]
I am sorry, but if I add the Nuget I get this error in my AppDelegate.cs:
![image](https://user-images.githubusercontent.com/2002916/124257363-959bed00-db2c-11eb-8bd3-49865c361b1c.png)

I removed the Nuget from Microsoft before.
