### ISSUE TITLE
clang build errors

### ISSUE THREAD

**Issue by DennisWelu** [nor0x/AppCenter-XMac#19]
With both the 4.0.0 and 4.1.0 version, when I install either nor0x.AppCenter.Crashes or nor0x.AppCenter.Analytics (have not tried others) into the project I get 2 build errors. 

- clang : error : linker command failed with exit code 1 (use -v to see invocation)
- MMP : error MM5309: Failed to execute the tool 'clang', it failed with an error code '1'. Please check the build log for details.

Looking into the build output...this is in part of the output:

-     MMP : warning MM2013: Failed to resolve the reference to \"Microsoft.AppCenter.MacOS.Bindings, Version=1.0.7676.24434, Culture=neutral, PublicKeyToken=null\", referenced in \"Microsoft.AppCenter.Crashes.MacOS.Bindings, Version=1.0.7676.24436, Culture=neutral, PublicKeyToken=null\". The app will not include the referenced assembly, and may fail at runtime.
-     MMP : warning MM2013: Failed to resolve the reference to \"Microsoft.AppCenter.MacOS.Bindings, Version=1.0.7676.24434, Culture=neutral, PublicKeyToken=null\", referenced in \"Microsoft.AppCenter.Crashes, Version=1.0.7676.24437, Culture=neutral, PublicKeyToken=null\". The app will not include the referenced assembly, and may fail at runtime.

I'm building with Visual Studio for Mac 8.8.4, Mono 6.12.0.113, Xamarin.Mac 7.0.0.15. On MacOS 10.15.7 and using XCode 12.2. 

I've re-read the readme a few times. I don't know what else I might be missing. So am assuming some kind of bug?  If I look in the nuget cache folder I see lib folders with dlls in it like "Microsoft.AppCenter.Analytics.MacOS.Bindings.dll". So I'm not sure if there is a disconnect in the name of the dll reference there somewhere.

**Comment by nor0x** [comment]
do you have the linker enabled in the macOS project settings? I'm already working to get the linker support ready for the packages

**Comment by DennisWelu** [comment]
Linking is disabled. Good to hear about the work you are doing to support it! I will try again after I update XCode to 12.3 in the near future.

**Comment by DennisWelu** [comment]
Finally got around to trying with the latest XCode (12.4), Xamarin.Mac (7.4), etc. Unfortunately, still seeing the same output on build.

**Comment by nor0x** [comment]
@DennisWelu could you try the latest version `4.3.1`

**Comment by DennisWelu** [comment]
@nor0x Finally got to testing this again, and hey it works! Nice job, @nor0x . Thanks again.
