### ISSUE TITLE
Compile error: The command  exited with code 1

### ISSUE THREAD

**Issue by Sergtek** [nor0x/AppCenter-XMac#26]
I have the linker disabled, I have migrated my packages.config to PackageReference and I am using the latest version of the nuget nor0x.AppCenter 4.4.0-XMAC, I have compiled, recompiled, cleaned the solution, deleted the bin and obj folder and restarted visual studio but the following error cannot be solved:

Compilation error The command "cd bin \ Debug \ myApp \ Contents \ Frameworks \ AppCenter.framework \; rm AppCenter; ln -s Versions \ A \ AppCenter AppCenter" exited with code 1.

Anyone have any idea what can happen? thanks for your attention.

**Comment by nor0x** [comment]
this code now lives in the official repository https://github.com/microsoft/appcenter-sdk-dotnet

if you still have this issue - please open a new one here:
https://github.com/microsoft/appcenter-sdk-dotnet/issues/new/choose
